build:
    image: default-bionic
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true

checks:
    php: true
coding_style:
    php: {  }

tools:
    php_analyzer: true
    php_changetracking: true
    external_code_coverage:
        timeout: 600

filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
