<?php


namespace Cypress\PatchManagerBundle\Exception;

use Exception;
use PhpCollection\Sequence;

class MissingKeysRequest extends \Exception
{
    public function __construct(
        array $operationData,
        Sequence $missingKeys,
        $message = "",
        $code = 0,
        Exception $previous = null
    ) {
        $message = sprintf("You passed an operation without a required key to the PatchManager. The json should contain
            the following keys: %s. While you passed: %s", implode(', ', $missingKeys->all()), json_encode($operationData));
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }
} 